-- MySQL Script generated by MySQL Workbench
-- Mon Mar 22 19:29:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema soft_mlmbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soft_mlmbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soft_mlmbd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `soft_mlmbd` ;

-- -----------------------------------------------------
-- Table `soft_mlmbd`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`producto` (
  `ProductoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Existencia` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Imagen` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`ProductoID`),
  UNIQUE INDEX `nombre_producto_UNIQUE` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`tipoempleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`tipoempleado` (
  `TipoEmpleadoID` INT NOT NULL AUTO_INCREMENT,
  `TipoEmpleado` VARCHAR(45) NOT NULL,
  `NivelAcceso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`TipoEmpleadoID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`empleado` (
  `EmpleadoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `FechaIngreso` DATE NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `TipoEmpleadoID` INT NOT NULL,
  PRIMARY KEY (`EmpleadoID`),
  INDEX `fkTipoEmpleado_idx` (`TipoEmpleadoID` ASC) VISIBLE,
  CONSTRAINT `fkTipoEmpleado`
    FOREIGN KEY (`TipoEmpleadoID`)
    REFERENCES `soft_mlmbd`.`tipoempleado` (`TipoEmpleadoID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`venta` (
  `VentaID` INT NOT NULL AUTO_INCREMENT,
  `FechaVenta` DATE NOT NULL,
  `EmpleadoID` INT NOT NULL,
  PRIMARY KEY (`VentaID`),
  INDEX `fkempleados_idx` (`EmpleadoID` ASC) VISIBLE,
  CONSTRAINT `fkempleados`
    FOREIGN KEY (`EmpleadoID`)
    REFERENCES `soft_mlmbd`.`empleado` (`EmpleadoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`detalleventa` (
  `VentaID` INT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Cantidad` INT NOT NULL,
  `ProductoID` INT NOT NULL,
  PRIMARY KEY (`VentaID`),
  INDEX `fkproducto_idx` (`ProductoID` ASC) VISIBLE,
  CONSTRAINT `fkproduct`
    FOREIGN KEY (`ProductoID`)
    REFERENCES `soft_mlmbd`.`producto` (`ProductoID`),
  CONSTRAINT `fkventa`
    FOREIGN KEY (`VentaID`)
    REFERENCES `soft_mlmbd`.`venta` (`VentaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
