/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import DataBase.ConexionDB;
import DataBase.ProcedimientosDAO;
import ObjetosNegocio.Producto;
import ObjetosNegocio.TipoProductos;
import alarmas.AlertaError;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author AlfredoPerez
 */
public class JDialogInventariarProducto extends javax.swing.JDialog {

    private Producto producto;
    private List<TipoProductos> listaTipoProductos;
    private ProcedimientosDAO procedimientosDAO;
    private static ResultSet resultSet;
    
    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     * @param producto
     */
    public JDialogInventariarProducto(java.awt.Frame parent, boolean modal, Producto producto) {
        super(parent, modal);
        this.initComponents();
        this.procedimientosDAO = new ProcedimientosDAO(ConexionDB.conexion);
        this.producto = producto;
        this.cargarDatosProducto();
    }
    
    private void cargarDatosProducto(){
        this.txtID.setText(String.valueOf(producto.getID()));
        this.txtNombre.setText(producto.getNombre());
        this.txtTipo.setText(producto.getTipoProducto());
        this.txtExistencia.setText(String.valueOf(producto.getExistencia()));
        BufferedImage imagen;
            if(producto.getFotoProducto() != null){
                try {
                    imagen = ImageIO.read(new ByteArrayInputStream(producto.getFotoProducto()));
                    ImageIcon imagenProducto1 = new ImageIcon(imagen);
                    this.imagenProducto.setImagen(imagenProducto1);
                } 
                catch (IOException ex) {new AlertaError(null, rootPaneCheckingEnabled, "Error al cargar la imagen :(").setVisible(true);}
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenidoInventariarProducto = new javax.swing.JPanel();
        etiquetaInventariarProducto = new javax.swing.JLabel();
        etiquetaCantidadInventariar = new javax.swing.JLabel();
        panelProductoInventariar = new javax.swing.JPanel();
        etiquetaID = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaTipo = new javax.swing.JLabel();
        etiquetaExistencia = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        imagenProducto = new rojerusan.RSPanelImage();
        txtCantidadInventariar = new javax.swing.JSpinner();
        botonCancelar = new componentes.BotonPersonalizado();
        botonAceptar = new componentes.BotonPersonalizado();
        panelFondo2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenidoInventariarProducto.setBackground(new java.awt.Color(255, 255, 255));
        panelContenidoInventariarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaInventariarProducto.setBackground(new java.awt.Color(0, 0, 0));
        etiquetaInventariarProducto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        etiquetaInventariarProducto.setText("Inventariar Producto");
        panelContenidoInventariarProducto.add(etiquetaInventariarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 11, -1, -1));

        etiquetaCantidadInventariar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetaCantidadInventariar.setForeground(new java.awt.Color(153, 153, 153));
        etiquetaCantidadInventariar.setText("Cantidad a inventariar: ");
        etiquetaCantidadInventariar.setPreferredSize(new java.awt.Dimension(190, 30));
        panelContenidoInventariarProducto.add(etiquetaCantidadInventariar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 30));

        panelProductoInventariar.setBackground(new java.awt.Color(204, 204, 204));

        etiquetaID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetaID.setText("ID: ");

        etiquetaNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetaNombre.setText("Nombre: ");

        etiquetaTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetaTipo.setText("Tipo: ");

        etiquetaExistencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetaExistencia.setText("Existencia: ");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtID.setPreferredSize(new java.awt.Dimension(30, 25));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(30, 25));

        txtExistencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtExistencia.setPreferredSize(new java.awt.Dimension(30, 25));

        txtTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTipo.setPreferredSize(new java.awt.Dimension(30, 25));

        imagenProducto.setImagen(new javax.swing.ImageIcon(getClass().getResource("/img/agregarfotoProducto.png"))); // NOI18N
        imagenProducto.setPreferredSize(new java.awt.Dimension(170, 133));

        javax.swing.GroupLayout panelProductoInventariarLayout = new javax.swing.GroupLayout(panelProductoInventariar);
        panelProductoInventariar.setLayout(panelProductoInventariarLayout);
        panelProductoInventariarLayout.setHorizontalGroup(
            panelProductoInventariarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoInventariarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelProductoInventariarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaExistencia)
                    .addComponent(etiquetaID)
                    .addComponent(etiquetaNombre)
                    .addComponent(etiquetaTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductoInventariarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(imagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        panelProductoInventariarLayout.setVerticalGroup(
            panelProductoInventariarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoInventariarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelProductoInventariarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelProductoInventariarLayout.createSequentialGroup()
                        .addGroup(panelProductoInventariarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelProductoInventariarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelProductoInventariarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoInventariarLayout.createSequentialGroup()
                                .addComponent(etiquetaTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etiquetaExistencia))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoInventariarLayout.createSequentialGroup()
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );

        panelContenidoInventariarProducto.add(panelProductoInventariar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 580, 180));

        txtCantidadInventariar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        txtCantidadInventariar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCantidadInventariar.setPreferredSize(new java.awt.Dimension(100, 30));
        panelContenidoInventariarProducto.add(txtCantidadInventariar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 130, -1));

        botonCancelar.setText("Cancelar");
        botonCancelar.setColorHover(new java.awt.Color(45, 116, 191));
        botonCancelar.setColorNormal(new java.awt.Color(58, 103, 201));
        botonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCancelar.setPreferredSize(new java.awt.Dimension(160, 40));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelContenidoInventariarProducto.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 90, 30));

        botonAceptar.setText("Aceptar");
        botonAceptar.setColorHover(new java.awt.Color(45, 116, 191));
        botonAceptar.setColorNormal(new java.awt.Color(58, 103, 201));
        botonAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAceptar.setPreferredSize(new java.awt.Dimension(160, 40));
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        panelContenidoInventariarProducto.add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 90, 30));

        getContentPane().add(panelContenidoInventariarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 400));

        panelFondo2.setBackground(new java.awt.Color(29, 48, 107));
        panelFondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private boolean validarCantidadInventariar(){
       return Integer.valueOf(txtCantidadInventariar.getValue().toString()) > 0;
    }
    
    
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(validarCantidadInventariar()){
            
            producto.setExistencia(producto.getExistencia()+ Integer.valueOf(txtCantidadInventariar.getValue().toString()));
         
            try{
                procedimientosDAO.actualizarProducto(producto);
                this.dispose();
            } 
            catch (SQLException ex) {new AlertaError(null, rootPaneCheckingEnabled, "Algo salio mal al conectarse con la base de datos :(").setVisible(true);}
        }   
        else{new AlertaError(null, rootPaneCheckingEnabled, "No se puede inventariar '0' o 'numeros negativos'").setVisible(true);}
    }//GEN-LAST:event_botonAceptarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.BotonPersonalizado botonAceptar;
    private componentes.BotonPersonalizado botonCancelar;
    private javax.swing.JLabel etiquetaCantidadInventariar;
    private javax.swing.JLabel etiquetaExistencia;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JLabel etiquetaInventariarProducto;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTipo;
    private rojerusan.RSPanelImage imagenProducto;
    private javax.swing.JPanel panelContenidoInventariarProducto;
    private javax.swing.JPanel panelFondo2;
    private javax.swing.JPanel panelProductoInventariar;
    private javax.swing.JSpinner txtCantidadInventariar;
    private javax.swing.JLabel txtExistencia;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTipo;
    // End of variables declaration//GEN-END:variables
}
