/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import DataBase.ConexionDB;
import DataBase.ProcedimientosDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlfredoPerez
 */
public class JFrameAdministarCatalago extends javax.swing.JFrame {

    private final ProcedimientosDAO procedimientosDAO;
    private static ResultSet resultSet;
    
    /**
     * Creates new form JFrameAdministarCatalago
     */
    public JFrameAdministarCatalago() {
        procedimientosDAO = new ProcedimientosDAO(ConexionDB.conexion);
        initComponents();
        llenarTablaProductos();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        rSPanelEffect1 = new rojerusan.RSPanelEffect();
        jPanel1 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSPanelImage3 = new rojerusan.RSPanelImage();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new rojerusan.RSTableMetro();
        rSButtonShade1 = new rscomponentshade.RSButtonShade();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(15, 110, 252));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(102, 102, 255));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_3);

        rSPanelEffect1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 92, 179));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 40));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/img/administrarCatalago/mas.png"))); // NOI18N
        rSPanelImage1.setPreferredSize(new java.awt.Dimension(40, 40));
        rSPanelImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rSPanelImage1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar producto");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        rSPanelEffect1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 92, 179));
        jPanel2.setPreferredSize(new java.awt.Dimension(270, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/img/administrarCatalago/solicitar.png"))); // NOI18N
        rSPanelImage2.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inventariar producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        rSPanelEffect1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 92, 179));
        jPanel3.setPreferredSize(new java.awt.Dimension(270, 40));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/img/administrarCatalago/borrar.png"))); // NOI18N
        rSPanelImage3.setPreferredSize(new java.awt.Dimension(40, 40));
        rSPanelImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rSPanelImage3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelImage3Layout = new javax.swing.GroupLayout(rSPanelImage3);
        rSPanelImage3.setLayout(rSPanelImage3Layout);
        rSPanelImage3Layout.setHorizontalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        rSPanelImage3Layout.setVerticalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(rSPanelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Eliminar producto");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        rSPanelEffect1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Soft-MLM");
        rSPanelEffect1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
        rSPanelEffect1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, 20));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"234234", "asdasd", "asd", "asdasd", "asdasd"},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio venta", "Existencia", "Descripcion"
            }
        ));
        tablaProductos.setAltoHead(30);
        tablaProductos.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tablaProductos.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tablaProductos.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tablaProductos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tablaProductos.setFuenteFilas(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tablaProductos.setFuenteFilasSelect(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tablaProductos.setFuenteHead(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tablaProductos.setGrosorBordeFilas(0);
        tablaProductos.setRowHeight(25);
        tablaProductos.setRowMargin(0);
        jScrollPane1.setViewportView(tablaProductos);

        rSButtonShade1.setBackground(new java.awt.Color(0, 0, 0));
        rSButtonShade1.setBorder(null);
        rSButtonShade1.setText("Salir");
        rSButtonShade1.setBgHover(new java.awt.Color(0, 0, 84));
        rSButtonShade1.setBgShadeHover(new java.awt.Color(0, 0, 84));
        rSButtonShade1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rSButtonShade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShade1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LISTA DE PRODUCTOS");

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addComponent(rSPanelEffect1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSButtonShade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel5)
                        .addContainerGap(232, Short.MAX_VALUE))))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelEffect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSButtonShade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonShade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShade1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonShade1ActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        JDialogAgregarProducto agregarProducto = new JDialogAgregarProducto(this, rootPaneCheckingEnabled);
        llenarTablaProductos();
    }//GEN-LAST:event_jLabel1MousePressed

    private void rSPanelImage1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelImage1MousePressed
        JDialogAgregarProducto agregarProducto = new JDialogAgregarProducto(this, rootPaneCheckingEnabled);
        llenarTablaProductos();
    }//GEN-LAST:event_rSPanelImage1MousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        JDialogAgregarProducto agregarProducto = new JDialogAgregarProducto(this, rootPaneCheckingEnabled);
        llenarTablaProductos();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        //
    }//GEN-LAST:event_jLabel3MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void rSPanelImage3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelImage3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSPanelImage3MousePressed

    public void llenarTablaProductos(){
        clearTable(tablaProductos);
        String sql = "SELECT * FROM soft_mlmbd.producto";
        DefaultTableModel tablaModelo = (DefaultTableModel) tablaProductos.getModel();
        try {
            resultSet = procedimientosDAO.ejecututarQuery(sql);
            while(resultSet.next()){
                Object[] datos = new Object[5];
                datos[0] = resultSet.getInt(1);
                datos[1] = resultSet.getString(2);
                datos[2] = resultSet.getDouble(3);
                datos[3] = resultSet.getInt(4);
                datos[4] = resultSet.getString(5);
                
                tablaModelo.addRow(datos);
            }
           
        } catch (SQLException ex) {
            System.out.println("Error: "+ex.getMessage());
        }
    }
    
    public void clearTable(JTable tabla) {
        
        while(tabla.getRowCount() > 0){
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private rscomponentshade.RSButtonShade rSButtonShade1;
    private rojerusan.RSPanelEffect rSPanelEffect1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSPanelImage rSPanelImage2;
    private rojerusan.RSPanelImage rSPanelImage3;
    private rojerusan.RSTableMetro tablaProductos;
    // End of variables declaration//GEN-END:variables
}
