-- MySQL Script generated by MySQL Workbench
-- Thu Apr  8 00:34:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soft_mlmbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soft_mlmbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soft_mlmbd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `soft_mlmbd` ;

-- -----------------------------------------------------
-- Table `soft_mlmbd`.`tipoproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`tipoproducto` (
  `TipoProductoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`TipoProductoID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`producto` (
  `ProductoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `TipoProductoID` INT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Existencia` INT NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Imagen` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`ProductoID`),
  UNIQUE INDEX `ProductoID_UNIQUE` (`ProductoID` ASC) VISIBLE,
  INDEX `TipoProductoID_idx` (`TipoProductoID` ASC) VISIBLE,
  CONSTRAINT `TipoProductoID`
    FOREIGN KEY (`TipoProductoID`)
    REFERENCES `soft_mlmbd`.`tipoproducto` (`TipoProductoID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`tipoempleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`tipoempleado` (
  `TipoEmpleadoID` INT NOT NULL AUTO_INCREMENT,
  `TipoEmpleado` VARCHAR(45) NOT NULL,
  `NivelAcceso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`TipoEmpleadoID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`empleado` (
  `EmpleadoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `FechaIngreso` DATE NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `TipoEmpleadoID` INT NOT NULL,
  PRIMARY KEY (`EmpleadoID`),
  INDEX `fkTipoEmpleado_idx` (`TipoEmpleadoID` ASC) VISIBLE,
  CONSTRAINT `fkTipoEmpleado`
    FOREIGN KEY (`TipoEmpleadoID`)
    REFERENCES `soft_mlmbd`.`tipoempleado` (`TipoEmpleadoID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`venta` (
  `VentaID` INT NOT NULL AUTO_INCREMENT,
  `FechaVenta` DATE NOT NULL,
  `EmpleadoID` INT NOT NULL,
  PRIMARY KEY (`VentaID`),
  INDEX `fkempleados_idx` (`EmpleadoID` ASC) VISIBLE,
  CONSTRAINT `fkempleados`
    FOREIGN KEY (`EmpleadoID`)
    REFERENCES `soft_mlmbd`.`empleado` (`EmpleadoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `soft_mlmbd`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft_mlmbd`.`detalleventa` (
  `VentaID` INT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Cantidad` INT NOT NULL,
  `ProductoID` INT NOT NULL,
  INDEX `fkproducto_idx` (`ProductoID` ASC) VISIBLE,
  INDEX `fkventa` (`VentaID` ASC) VISIBLE,
  CONSTRAINT `fkproduct`
    FOREIGN KEY (`ProductoID`)
    REFERENCES `soft_mlmbd`.`producto` (`ProductoID`),
  CONSTRAINT `fkventa`
    FOREIGN KEY (`VentaID`)
    REFERENCES `soft_mlmbd`.`venta` (`VentaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `soft_mlmbd` ;

-- -----------------------------------------------------
-- procedure sp_actualizarProducto
-- -----------------------------------------------------

DELIMITER $$
USE `soft_mlmbd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_actualizarProducto`(ID int,Nombre varchar(45), TipoProductoID int, Precio double,Existencia int, Descripcion varchar(200), Imagen blob)
BEGIN
  UPDATE `soft_mlmbd`.`producto` SET `Nombre` = Nombre, `TipoProductoID` = TipoProductoID, `Precio` = Precio, `Existencia` = Existencia, `Descripcion` = Descripcion, `Imagen`=Imagen 
  WHERE (`ProductoID` = ID);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_agregarProducto
-- -----------------------------------------------------

DELIMITER $$
USE `soft_mlmbd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_agregarProducto`(Nombre varchar(45), TipoProductoID int, Precio double,Existencia int, Descripcion varchar(200), Imagen blob)
BEGIN
    INSERT INTO `soft_mlmbd`.`producto` (`Nombre`, `TipoProductoID`, `Precio`, `Existencia`, `Descripcion`, `Imagen`) VALUES (Nombre, TipoProductoID, Precio, Existencia, Descripcion, Imagen);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_consultaProductos
-- -----------------------------------------------------

DELIMITER $$
USE `soft_mlmbd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_consultaProductos`()
BEGIN
     SELECT P.ProductoID,
		   P.Nombre,
		   TP.Nombre as 'TipoProducto',
		   P.Precio,
		   P.Existencia,
		   P.Descripcion,
           P.Imagen
	FROM soft_mlmbd.producto P INNER JOIN soft_mlmbd.tipoproducto TP ON P.TipoProductoID = TP.TipoProductoID
    ORDER BY P.ProductoID;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
